name: test2
on:
  pull_request:
  push:

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }}
      - uses: reviewdog/action-golangci-lint@v2.6.1
        with:
          go_version_file: go.mod
          fail_on_error: true
